INSERT INTO ae_game_configs (category, raw_js) VALUES ('VEHS', 'const VEHS=[

  {id:''v_mega_sedan'', n:''Titan Limousine'', cat:''lux'', p:65000, cost:28000, time:14000, q:0.18, ico:''🕴️'', req:[''c_bat_solid'', ''c_sens_ai'', ''c_lux_seats'']},
  {id:''v_eco_city'', n:''Metro Sprinter'', cat:''eco'', p:18000, cost:9000, time:3500, q:0.04, ico:''🚙'', req:[''c_bat_base'', ''c_mot_base'']},
  {id:''v_hyper_truck'', n:''Ares Cyber-Truck'', cat:''suv'', p:85000, cost:42000, time:18000, q:0.25, ico:''🚜'', req:[''c_bat_solid'', ''c_mot_hp'', ''c_sens_adv'']},
  {id:''v_sport_gt'', n:''Vortex GT'', cat:''sport'', p:120000, cost:60000, time:22000, q:0.3, ico:''🏎️'', req:[''c_bat_solid'', ''c_mot_hp'', ''c_sens_ai'']},
  {id:''v_family_van'', n:''Voyager Van'', cat:''mid'', p:35000, cost:18000, time:7000, q:0.08, ico:''🚐'', req:[''c_bat_adv'', ''c_mot_base'']},
  {id:''v_retro_cabrio'', n:''Neo-Retro Cabrio'', cat:''sport'', p:55000, cost:25000, time:9000, q:0.15, ico:''🚘'', req:[''c_bat_adv'', ''c_mot_hp'']},
  {id:''v_safari_4x4'', n:''Safari Offroader'', cat:''suv'', p:48000, cost:26000, time:11000, q:0.12, ico:''🏕️'', req:[''c_bat_adv'', ''c_mot_adv'', ''c_lux_seats'']},
  {id:''v_micro_pod'', n:''Pod Commuter'', cat:''eco'', p:12000, cost:5000, time:2500, q:0.03, ico:''🛸'', req:[''c_bat_base'', ''c_sens_adv'']},
  {id:''v_lunar_rover'', n:''Lunar Concept'', cat:''lux'', p:150000, cost:80000, time:30000, q:0.4, ico:''🌕'', req:[''c_bat_solid'', ''c_mot_hp'', ''c_sens_ai'']},
  {id:''v_ delivery_box'', n:''Cargo-Bot M1'', cat:''mid'', p:28000, cost:12000, time:5000, q:0.05, ico:''📦'', req:[''c_bat_adv'', ''c_sens_ai'']},

  {id:''polo'',   name:''Polo Neo'',   e:''🚙'',seg:''Kleinstwagen'',price:18900, pc:9000, t:120,cap:8,req:[''eng_base'',''body_st'',''chassis'']},
  {id:''golf'',   name:''Golf X'',     e:''🚗'',seg:''Kompakt'',     price:28500, pc:14000,t:150,cap:6,req:[''eng_base'',''body_st'',''chassis'',''int_base'']},
  {id:''passat'', name:''Passat Evo'', e:''🚕'',seg:''Mittelklasse'',price:38000, pc:19000,t:180,cap:4,req:[''eng_v6'',''body_alu'',''chassis'']},
  {id:''tiguan'', name:''Tiguan Pro'', e:''🛻'',seg:''SUV'',         price:45000, pc:22000,t:200,cap:4,req:[''eng_v6'',''body_alu'',''awd'']},
  {id:''touareg'',name:''Touareg X'',  e:''🚐'',seg:''Luxury SUV'',  price:75000, pc:38000,t:240,cap:2,req:[''eng_v6'',''body_alu'',''awd'',''int_lux'']},
  {id:''id4'',    name:''ID.4 Evo'',   e:''⚡'',seg:''E-SUV'',       price:52000, pc:28000,t:220,cap:3,req:[''eng_elec'',''body_alu'',''battery'']},
  {id:''arteon'', name:''Arteon R'',   e:''🏁'',seg:''Sport'',       price:58000, pc:29000,t:240,cap:2,req:[''eng_v6'',''body_alu'',''susp_sp'']},
  {id:''id_buzz'',name:''ID. Buzz'',   e:''🚌'',seg:''E-Van'',       price:65000, pc:34000,t:260,cap:2,req:[''eng_elec'',''body_alu'',''battery'',''infotn'']},
  {id:''phaeton'',name:''Phaeton II'', e:''🚀'',seg:''Ultra Luxury'',price:120000,pc:58000,t:480,cap:1,req:[''eng_v8'',''body_cfk'',''int_lux'',''adas'']},
  {id:''beetle'', name:''Beetle-E'',   e:''🐞'',seg:''E-Kult'',      price:35000, pc:16000,t:160,cap:4,req:[''eng_elec'',''body_st'',''infotn'']},
  {id:''micro_e'',name:''Micro-E'',e:''🚗'',seg:''Kleinstwagen'',price:15000,pc:7000,t:100,cap:6,req:[''eng_elec'',''body_st'']},
  {id:''offroad'',name:''Offroad 4x4'',e:''🚙'',seg:''SUV'',price:55000,pc:28000,t:220,cap:3,req:[''eng_v6'',''body_st'',''awd'']},
  {id:''lux_van'',name:''Luxury Van'',e:''🚐'',seg:''Luxury Van'',price:85000,pc:42000,t:250,cap:2,req:[''eng_v6'',''body_alu'',''int_lux'']},
  {id:''hyper_v10'',name:''Hypercar V10'',e:''🏎️'',seg:''Ultra Luxury'',price:250000,pc:110000,t:500,cap:1,req:[''eng_v10'',''body_cfk'',''susp_sp'',''int_lux'']},
  {id:''aero_con'',name:''Aero Concept'',e:''🛸'',seg:''Sport'',price:95000,pc:45000,t:280,cap:2,req:[''eng_elec'',''body_cfk'',''aero_kit'']},
];');
INSERT INTO ae_game_configs (category, raw_js) VALUES ('COMPS', 'const COMPS=[

  {id:''c_bat_quantum'', n:''Quantum Batterie'', cat:''bat'', cost:15000, time:8000, q:0.3, ico:''🔋'', reqPt:5000},
  {id:''c_mot_hyper'', n:''HyperDrive Motor'', cat:''mot'', cost:12000, time:6000, q:0.25, ico:''⚙️'', reqPt:4000},
  {id:''c_sens_quantum'', n:''Quantum Sensoren'', cat:''sens'', cost:8000, time:4000, q:0.2, ico:''📡'', reqPt:3500},
  {id:''c_lux_holo'', n:''Holo-Cockpit'', cat:''lux'', cost:5000, time:3000, q:0.15, ico:''🌌'', reqPt:2000},
  {id:''c_chassis_carbon'', n:''Carbon Chassis'', cat:''body'', cost:6000, time:3500, q:0.12, ico:''🏎️'', reqPt:1500},
  {id:''c_chassis_titanium'', n:''Titanium Frame'', cat:''body'', cost:10000, time:5000, q:0.2, ico:''🛡️'', reqPt:3000},
  {id:''c_aero_wings'', n:''Aero-Flaps'', cat:''body'', cost:2500, time:1500, q:0.05, ico:''🪽'', reqPt:1000},
  {id:''c_lux_massage'', n:''Massage-Sitze'', cat:''lux'', cost:3000, time:2000, q:0.1, ico:''💆'', reqPt:1200},
  {id:''c_bat_solar'', n:''Solar-Dach Integration'', cat:''bat'', cost:7500, time:4500, q:0.15, ico:''☀️'', reqPt:2500},
  {id:''c_sens_lidar_v2'', n:''LiDAR 360° Array'', cat:''sens'', cost:6500, time:3000, q:0.15, ico:''👁️'', reqPt:2000},

  {id:''eng_base'',cat:''Antrieb'',   name:''4-Zyl. Benziner'', icon:''🔧'',cost:50000, inc:15000,max:10,req:{steel:50,aluminum:20}},
  {id:''eng_v6'',  cat:''Antrieb'',   name:''V6 3.0L'',         icon:''🔥'',cost:150000,inc:40000,max:8, req:{steel:80,aluminum:40}},
  {id:''eng_dsl'', cat:''Antrieb'',   name:''Diesel TDI'',      icon:''⛽'',cost:80000, inc:20000,max:8, req:{steel:60,aluminum:30}},
  {id:''eng_elec'',cat:''Antrieb'',   name:''E-Motor'',         icon:''⚡'',cost:300000,inc:80000,max:10,req:{elec:100,aluminum:50}},
  {id:''eng_hyb'', cat:''Antrieb'',   name:''Hybrid'',          icon:''🌿'',cost:250000,inc:60000,max:6, req:{elec:80,steel:40}},
  {id:''eng_v8'',  cat:''Antrieb'',   name:''V8 Sport 5.0L'',  icon:''🏎️'',cost:500000,inc:100000,max:5,req:{steel:120,aluminum:80}},
  {id:''trans'',   cat:''Antrieb'',   name:''Getriebewerk'',    icon:''⚙️'',cost:180000,inc:45000,max:6, req:{steel:70,aluminum:40}},
  {id:''body_st'', cat:''Karosserie'',name:''Stahlkarosserie'', icon:''🔩'',cost:40000, inc:10000,max:10,req:{steel:100}},
  {id:''body_alu'',cat:''Karosserie'',name:''Aluminiumrahmen'', icon:''🪨'',cost:120000,inc:30000,max:8, req:{aluminum:80}},
  {id:''body_cfk'',cat:''Karosserie'',name:''Carbon Fiber'',    icon:''🖤'',cost:800000,inc:150000,max:5,req:{aluminum:100,elec:20}},
  {id:''press'',   cat:''Karosserie'',name:''Presswerk 4000t'', icon:''🏗️'',cost:200000,inc:50000,max:6, req:{steel:200,energy:50}},
  {id:''chassis'', cat:''Fahrwerk'',  name:''Basis-Plattform'', icon:''🔗'',cost:60000, inc:15000,max:10,req:{steel:80,rubber:30}},
  {id:''susp_sp'', cat:''Fahrwerk'',  name:''Sport-Fahrwerk'',  icon:''🏁'',cost:180000,inc:40000,max:6, req:{steel:60,elec:30}},
  {id:''awd'',     cat:''Fahrwerk'',  name:''Allradantrieb'',   icon:''🌀'',cost:250000,inc:60000,max:5, req:{steel:100,elec:40}},
  {id:''axles'',   cat:''Fahrwerk'',  name:''Achswerk'',        icon:''🔄'',cost:100000,inc:25000,max:8, req:{steel:90,aluminum:30}},
  {id:''int_base'',cat:''Innenraum'', name:''Std. Interieur'',  icon:''🪑'',cost:30000, inc:8000, max:10,req:{plastic:80,rubber:20}},
  {id:''int_lux'', cat:''Innenraum'', name:''Luxus-Ausstattung'',icon:''💎'',cost:400000,inc:80000,max:6,req:{plastic:100,elec:50}},
  {id:''infotn'',  cat:''Innenraum'', name:''Infotainment'',    icon:''📱'',cost:150000,inc:35000,max:8, req:{elec:100}},
  {id:''adas'',    cat:''Elektronik'',name:''ADAS Safety'',     icon:''🛡️'',cost:350000,inc:70000,max:6, req:{elec:150}},
  {id:''battery'', cat:''Elektronik'',name:''Batteriepaket'',   icon:''🔋'',cost:500000,inc:100000,max:8,req:{elec:200,aluminum:50}},
  {id:''paint'',   cat:''Fertigung'', name:''Lackierstraße'',   icon:''🎨'',cost:80000, inc:20000,max:10,req:{energy:30,plastic:40}},
  {id:''quality'', cat:''Fertigung'', name:''Qualitätskontrolle'',icon:''✅'',cost:120000,inc:25000,max:8,req:{elec:60}},
  {id:''weldbot'', cat:''Fertigung'', name:''Schweißroboter'',  icon:''🤖'',cost:300000,inc:60000,max:8, req:{steel:50,energy:80}},
  {id:''assembly'',cat:''Fertigung'', name:''Montageband'',     icon:''🏭'',cost:500000,inc:100000,max:6,req:{energy:100}},
  {id:''eng_v10'', cat:''Antrieb'',   name:''V10 Hyper'',       icon:''🔥'',cost:800000,inc:150000,max:4,req:{steel:150,aluminum:100}},
  {id:''bat_gra'', cat:''Elektronik'',name:''Graphen-Akku'',    icon:''🔋'',cost:900000,inc:120000,max:5,req:{elec:300,aluminum:100}},
  {id:''cam_mir'', cat:''Elektronik'',name:''Kamera-Spiegel'',  icon:''📷'',cost:200000,inc:40000,max:8,req:{elec:80}},
  {id:''aero_kit'',cat:''Karosserie'',name:''Aero-Kit'',        icon:''🌪️'',cost:300000,inc:50000,max:6,req:{plastic:100,aluminum:50}},
  {id:''solar_rf'',cat:''Innenraum'', name:''Solar-Dach'',      icon:''☀️'',cost:250000,inc:60000,max:6,req:{elec:100,aluminum:30}},
];');
INSERT INTO ae_game_configs (category, raw_js) VALUES ('RD', 'const RD=[

  {id:''rd_sales_ai'', n:''Sales-KI Optimierung'', cost:500000, pts:10000, ico:''🤖'', type:''salesRate'', val:0.15, d:''+15% Grundtempo im Verkauf.''},
  {id:''rd_prod_ai'', n:''Produktions-KI'', cost:500000, pts:10000, ico:''🦾'', type:''prodRate'', val:0.15, d:''+15% schnellere Produktion.''},
  {id:''rd_nano_paint'', n:''Nano-Lackierung'', cost:200000, pts:5000, ico:''🎨'', type:''priceMax'', val:0.05, d:''Kunden akzeptieren 5% höhere Preise.''},
  {id:''rd_marketing_psych'', n:''Kaufpsychologie'', cost:300000, pts:6000, ico:''🧠'', type:''salesRate'', val:0.10, d:''+10% Verkauf durch bessere Werbung.''},
  {id:''rd_logistics_drone'', n:''Drohnen-Logistik'', cost:400000, pts:8000, ico:''🚁'', type:''prodCost'', val:0.05, d:''-5% Produktionskosten.''},
  {id:''rd_eco_battery_recycling'', n:''Akku-Recycling'', cost:350000, pts:7000, ico:''♻️'', type:''esgBonus'', val:15, d:''+15 ESG Punkte permanent.''},
  {id:''rd_quantum_computing'', n:''Quanten-F&E'', cost:1000000, pts:20000, ico:''💻'', type:''rdSpeed'', val:0.2, d:''Generiert 20% mehr Forschungspunkte.''},
  {id:''rd_brand_cult'', n:''Kult-Markenstatus'', cost:800000, pts:15000, ico:''🌟'', type:''priceMax'', val:0.1, d:''Erhöht max. Verkaufspreise um 10%.''},
  {id:''rd_lobbying_expert'', n:''Lobby-Einfluss'', cost:600000, pts:12000, ico:''🏛️'', type:''lobbyBonus'', val:1, d:''Erhält doppelt so viele Lobby-Punkte.''},
  {id:''rd_zero_waste'', n:''Zero-Waste Produktion'', cost:450000, pts:9000, ico:''🗑️'', type:''esgBonus'', val:20, d:''+20 ESG Punkte.''},

  {cat:''🔧 Antrieb'',items:[{id:''turbo'',name:''Turboaufladung'',icon:''💨'',cost:100000,desc:''+15%''},{id:''fsi'',name:''Direkteinspritz.'',icon:''⛽'',cost:200000,desc:''-10% Verbr.''},{id:''startstop'',name:''Start-Stop'',icon:''🔄'',cost:150000,desc:''Stadt -8%''},{id:''mild48'',name:''48V Mildhybrid'',icon:''🌿'',cost:400000,desc:''CO2 -20%''},{id:''solid'',name:''Feststoffakku'',icon:''🔋'',cost:1000000,desc:''Reichw. +50%''}]},
  {cat:''🛡️ Sicherheit'',items:[{id:''abs'',name:''ABS & ESP'',icon:''🚦'',cost:80000,desc:''+NCAP''},{id:''airbag'',name:''Multi-Airbag'',icon:''🛡️'',cost:120000,desc:''8 Airbags''},{id:''lane'',name:''Lane Assist'',icon:''📏'',cost:200000,desc:''+Rep''},{id:''l2'',name:''Level 2 Auto.'',icon:''🤖'',cost:600000,desc:''Teilautonom''},{id:''l4'',name:''Level 4 Auto.'',icon:''🚗'',cost:2000000,desc:''Hochautonom''}]},
  {cat:''🏭 Produktion'',items:[{id:''lean'',name:''Lean Production'',icon:''⚡'',cost:150000,desc:''Kosten -8%''},{id:''jit'',name:''Just-in-Time'',icon:''📦'',cost:200000,desc:''Lager -30%''},{id:''aiq'',name:''KI Qualität'',icon:''🔬'',cost:400000,desc:''Ausschuss /2''},{id:''cobot'',name:''Koll. Roboter'',icon:''🤖'',cost:600000,desc:''+20% Out.''},{id:''giga'',name:''Gigapress'',icon:''🏗️'',cost:3000000,desc:''CF Guss''}]},
  {cat:''🧪 Material'',items:[{id:''alubody'',name:''Alu-Bauweise'',icon:''🪨'',cost:180000,desc:''-12% Gew.''},{id:''cfk'',name:''CfK Mischbau'',icon:''🖤'',cost:500000,desc:''-25kg''},{id:''recycle'',name:''Recycling'',icon:''♻️'',cost:250000,desc:''-10% Mat.''},{id:''nano'',name:''Nano-Beschicht.'',icon:''✨'',cost:350000,desc:''20J Schutz''}]},
  {cat:''💻 Digital'',items:[{id:''ota'',name:''OTA Updates'',icon:''📡'',cost:300000,desc:''Remote SW''},{id:''twin'',name:''Digit. Zwilling'',icon:''👯'',cost:800000,desc:''Entw. -40%''},{id:''5g'',name:''5G Konnektivität'',icon:''📶'',cost:400000,desc:''Connected''},{id:''ar'',name:''AR Design'',icon:''🕶️'',cost:600000,desc:''Design 2x''}]},
  {cat:''🌌 30 Bonus'',items:[{id:''holo_ui'',name:''Hologramm UI'',icon:''🖥️'',cost:500000,desc:''Rep +15''},{id:''hyper_charge'',name:''Hypercharge'',icon:''⚡'',cost:750000,desc:''Laden +50%''},{id:''bio_plas'',name:''Bio-Kunststoff'',icon:''🌱'',cost:400000,desc:''ESG +20''},{id:''ai_chassis'',name:''KI Chassis'',icon:''🧠'',cost:900000,desc:''Gewicht -15%''},{id:''solid_recyc'',name:''Feststoff-Recycling'',icon:''♻️'',cost:600000,desc:''Mat -15%''}]},
  {cat:''🌌 Bonus'',items:[{id:''holo_ui'',name:''Hologramm UI'',icon:''🖥️'',cost:500000,desc:''Rep +15''},{id:''hyper_charge'',name:''Hypercharge'',icon:''⚡'',cost:750000,desc:''Laden +50%''},{id:''bio_plas'',name:''Bio-Kunststoff'',icon:''🌱'',cost:400000,desc:''ESG +20''},{id:''ai_chassis'',name:''KI Chassis'',icon:''🧠'',cost:900000,desc:''Gewicht -15%''},{id:''solid_recyc'',name:''Feststoff-Recycling'',icon:''♻️'',cost:600000,desc:''Mat -15%''}]},
];');
INSERT INTO ae_game_configs (category, raw_js) VALUES ('EVENTS', 'const EVENTS=[

  {id:''ev_strike'', n:''Gewerkschaft streikt!'', t:''crisis'', d:''Die Mitarbeiter fordern mehr Lohn. Die Produktion steht für kurze Zeit still.'', ico:''🛑'', action:()=>{ G.money-=50000; notify(''Produktion gelähmt - €50.000 Verlust!'',''err''); }},
  {id:''ev_gov_grant'', n:''Staatliche Förderung'', t:''good'', d:''Die Regierung belohnt deine E-Auto-Strategie mit einem dicken Scheck.'', ico:''🏛️'', action:()=>{ G.money+=250000; notify(''+€250.000 Förderung!'',''ok''); }},
  {id:''ev_chip_shortage'', n:''Globale Chip-Krise'', t:''crisis'', d:''Halbleiter sind knapp! Die Produktionskosten steigen!'', ico:''💻'', action:()=>{ G.money-=100000; notify(''-€100.000 für alternative Chips!'',''err''); }},
  {id:''ev_viral_video'', n:''Virales Video'', t:''good'', d:''Ein TikTok-Video über dein Auto geht viral! Die Nachfrage explodiert.'', ico:''📱'', action:()=>{ G.share+=1; notify(''+1% Marktanteil durch Hype!'',''ok''); }},
  {id:''ev_recall'', n:''Rückruf-Aktion'', t:''crisis'', d:''Ein Bremspedal klemmt bei einem Modell. Teure Rückrufaktion nötig.'', ico:''🔧'', action:()=>{ G.money-=200000; G.rep=Math.max(0,G.rep-5); notify(''-€200.000 & Reputation sinkt'',''err''); }},
  {id:''ev_tech_breakthrough'', n:''Batterie-Durchbruch!'', t:''good'', d:''Das F&E-Team hat die Kapazität der Akkus maximiert!'', ico:''🔋'', action:()=>{ G.pts+=5000; notify(''+5000 Forschungspunkte!'',''ok''); }},
  {id:''ev_spy_caught'', n:''Spion gefasst'', t:''crisis'', d:''Ein feindlicher Spion hat Konstruktionspläne kopiert.'', ico:''🕵️'', action:()=>{ G.pts-=2000; notify(''Forschungsdaten gestohlen!'',''warn''); }},
  {id:''ev_design_award'', n:''Design Award 2026'', t:''good'', d:''Dein neues SUV-Modell gewinnt einen internationalen Designpreis.'', ico:''🏆'', action:()=>{ G.rep+=10; notify(''+10 Reputation!'',''ok''); }},
  {id:''ev_eco_protest'', n:''Klima-Proteste'', t:''crisis'', d:''Aktivisten blockieren deine Fabriken wegen zu hohem CO2-Ausstoß.'', ico:''🌍'', action:()=>{ G.money-=75000; notify(''Blockade kostet €75.000!'',''err''); }},
  {id:''ev_billionaire_order'', n:''Milliardärs-Flotte'', t:''good'', d:''Ein reicher Investor bestellt spontan 500 Luxus-Wagen!'', ico:''💎'', action:()=>{ G.money+=500000; notify(''+€500.000 Großauftrag!'',''ok''); }},

  {name:''Ölpreisschock'',     type:''crisis'',emoji:''🛢️'',desc:''Energiekosten +40%'',    effect:''energy_cost'', val:1.4,dur:120},
  {name:''E-Mobilitätsboom'',  type:''good'',  emoji:''⚡'',desc:''E-Fahrzeuge +30% Nachfr.'',effect:''ev_demand'',  val:1.3,dur:120},
  {name:''Wirtschaftskrise'',  type:''crisis'',emoji:''📉'',desc:''Preise -15%'',            effect:''price_cut'',   val:.85,dur:150},
  {name:''Technologieförder.'',type:''good'',  emoji:''🏛️'',desc:''+€500k Förderung'',       effect:''money'',       val:500000,dur:1},
  {name:''Globaler Streik'',   type:''crisis'',emoji:''✊'',desc:''Produktion -50%'',        effect:''prod_cut'',    val:.5,dur:90},
  {name:''Auto des Jahres'',   type:''good'',  emoji:''🏆'',desc:''Rep +20'',                effect:''rep'',         val:20,dur:1},
  {name:''Chip-Krise'',        type:''crisis'',emoji:''💻'',desc:''Elektronik -70%'',        effect:''chip'',        val:.3,dur:180},
  {name:''Batterie-Durchbruch'',type:''good'',emoji:''🔋'',desc:''E-Nachfrage +40%'',effect:''ev_demand'',val:1.4,dur:150},
  {name:''Hackerangriff'',type:''crisis'',emoji:''💻'',desc:''Prod. -30%'',effect:''prod_cut'',val:.7,dur:100},
  {name:''Neue Subvention'',type:''good'',emoji:''💰'',desc:''+€1M Förder.'',effect:''money'',val:1000000,dur:1},
  {name:''Schwerer Sturm'',type:''crisis'',emoji:''⛈️'',desc:''Kosten +20%'',effect:''price_cut'',val:1.2,dur:120},
  {name:''Rohstoff-Fund'',type:''good'',emoji:''⛏️'',desc:''Energie -40%'',effect:''energy_cost'',val:0.6,dur:150},
];');
INSERT INTO ae_game_configs (category, raw_js) VALUES ('ADS', 'const ADS=[

  {id:''ad_influencer'', n:''Influencer Sponsoring'', cost:50000, upk:500, dur:2400, l:''Social'', boost:0.18},
  {id:''ad_superbowl'', n:''Superbowl Spot'', cost:500000, upk:0, dur:600, l:''TV'', boost:0.40},
  {id:''ad_esports'', n:''E-Sports Team Sponsor'', cost:100000, upk:1000, dur:7200, l:''Web'', boost:0.12},
  {id:''ad_podcast'', n:''Business Podcast'', cost:25000, upk:250, dur:3600, l:''Radio'', boost:0.08},
  {id:''ad_hologram'', n:''Sky-Hologramm Werbung'', cost:250000, upk:2500, dur:1200, l:''Outdoor'', boost:0.25},

  {id:''tv'',  name:''TV Werbespots'',   icon:''📺'',cost:5000, eff:''+3% Nachfrage'',ev:.03},
  {id:''soc'', name:''Social Media'',    icon:''📱'',cost:3000, eff:''+5% Junge Käufer'',ev:.05},
  {id:''f1'',  name:''Motorsport'',      icon:''🏎️'',cost:25000,eff:''+8% Reputation'',ev:.08},
  {id:''infl'',name:''Influencer'',      icon:''⭐'',cost:8000, eff:''+6% Awareness'',ev:.06},
  {id:''iaa'', name:''Automesse IAA'',   icon:''🏛️'',cost:15000,eff:''+10% Händler'',ev:.10},
  {id:''eco'', name:''Grüne PR'',        icon:''🌿'',cost:6000, eff:''+7% ESG'',ev:.07},
  {id:''mag'', name:''Luxus-Magazin'',   icon:''💎'',cost:12000,eff:''+5% Premium'',ev:.05},
  {id:''esports'',name:''eSports Sponsoring'',icon:''🎮'',cost:10000, eff:''+6% Junge'',ev:.06},
  {id:''mega_ad'',name:''Mega-Event Spot'',   icon:''🏟️'',cost:35000, eff:''+12% Reach'',ev:.12},
  {id:''viral'',  name:''Viral-Kampagne'',    icon:''🦠'',cost:4000,  eff:''+5% Reichw.'',ev:.05},
  {id:''podcast'',name:''Tech-Podcast'',      icon:''🎧'',cost:7000,  eff:''+4% Premium'',ev:.04},
  {id:''popup'',  name:''Pop-Up-Store'',      icon:''🏪'',cost:20000, eff:''+8% Händler'',ev:.08},
];');
INSERT INTO ae_game_configs (category, raw_js) VALUES ('CEO_POOL', 'const CEO_POOL=[

  {id:''ceo_musk_parody'', n:''Elon Tusk'', bonus:''Marketing-Gott: Jede Werbung bringt +50% Wirkung, aber regelmäßige PR-Skandale.'', cost:80000, ic:''🚀''},
  {id:''ceo_supply_ninja'', n:''Takeshi K.'', bonus:''Lieferketten-Meister: Bauteile sind 15% billiger in der Produktion.'', cost:55000, ic:''🥷''},
  {id:''ceo_eco_warrior'', n:''Greta T.'', bonus:''Zero CO2: ESG-Score startet höher, staatliche Subventionen verdoppelt.'', cost:60000, ic:''🌱''},
  {id:''ceo_wallstreet'', n:''Gordon G.'', bonus:''Wolf of Börse: Aktienkauf ist 10% billiger, Übernahmen sind leichter.'', cost:120000, ic:''💼''},
  {id:''ceo_tech_genius'', n:''Ada L.'', bonus:''Tech-Pionier: +30% Grundgeschwindigkeit auf alle Forschungen.'', cost:95000, ic:''🧠''},

  {name:''Dr. Eva Müller'', emoji:''👩‍💼'',spec:''Effizienz'',  bonus:''Prod.kosten -10%'',effect:''prodCost'',val:.9},
  {name:''Hans Bergmann'',  emoji:''👨‍💼'',spec:''Expansion'', bonus:''Werke -20% Kosten'',effect:''facCost'', val:.8},
  {name:''Yuki Tanaka'',    emoji:''👩‍🔬'',spec:''Technologie'',bonus:''F&E +50% Speed'',   effect:''rdSpeed'', val:1.5},
  {name:''James Wilson'',   emoji:''👨‍💼'',spec:''Marketing'', bonus:''Werbeffekt +25%'',   effect:''adBoost'', val:1.25},
  {name:''Sofia Reyes'',    emoji:''👩‍💼'',spec:''Nachhalt.'',  bonus:''ESG +30'',           effect:''esg'',     val:1.3},
  {name:''Klaus Schneider'',emoji:''🧓'',  spec:''Finanzen'',  bonus:''Zinsen -50%'',       effect:''loanRate'',val:.5},
  {name:''Elena Techvision'',emoji:''🦾'',spec:''Technologie'',bonus:''F&E -20%'',effect:''rdCost'',val:.8},
  {name:''Markus Logistik'',emoji:''📦'',spec:''Lieferkette'',bonus:''Material +15%'',effect:''matBoost'',val:1.15},
  {name:''Stella Premium'',emoji:''✨'',spec:''Luxus'',bonus:''Rep +10%'',effect:''repBoost'',val:1.1},
  {name:''David Krisen'',emoji:''🛡️'',spec:''Risiko'',bonus:''Risiko -30%'',effect:''riskRed'',val:.7},
  {name:''Viktor Gold'',emoji:''🤑'',spec:''Finanzen'',bonus:''Margin +5%'',effect:''marginBoost'',val:1.05},
];');
INSERT INTO ae_game_configs (category, raw_js) VALUES ('RIVALS', 'const RIVALS=[
  {id:''bmw'',    n:''BMW GROUP'',    ic:''🔵'',co:''🇩🇪'',cl:''#1C69D4'',sh:18,ca:50e6,ag:.7},
  {id:''merc'',   n:''MERCEDES'',     ic:''⭐'',co:''🇩🇪'',cl:''#aaa'',   sh:16,ca:60e6,ag:.5},
  {id:''toyota'', n:''TOYOTA'',       ic:''🔴'',co:''🇯🇵'',cl:''#E62333'',sh:14,ca:80e6,ag:.6},
  {id:''ford'',   n:''FORD'',         ic:''🔷'',co:''🇺🇸'',cl:''#003499'',sh:11,ca:40e6,ag:.8},
  {id:''stell'',  n:''STELLANTIS'',   ic:''🌐'',co:''🇪🇺'',cl:''#FF8C00'',sh:9, ca:30e6,ag:.7},
  {id:''hyundai'',n:''HYUNDAI-KIA'',  ic:''🔶'',co:''🇰🇷'',cl:''#0057a8'',sh:10,ca:35e6,ag:.9},
  {id:''tesla'',  n:''TESLA'',        ic:''⚡'',co:''🇺🇸'',cl:''#cc0000'',sh:8, ca:70e6,ag:1.0},
  {id:''renault'',n:''RENAULT'',      ic:''💛'',co:''🇫🇷'',cl:''#FFCC00'',sh:7, ca:25e6,ag:.6},
];');
